# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---
# Tasks para instalacion de kamailio, https://www.kamailio.org/wiki/install/4.4.x/git
# Se clona el repositorio de kamailio
- name: Clone kamailio repository
  shell: >
          git clone --depth 1 --no-single-branch {{ item }} kamailio
          chdir=/usr/src/
  with_items:
          - "{{ kamailio_repo }}"
  register: command_result
  changed_when: "command_result.rc == 0"
  failed_when:
    - "'already exists' not in command_result.stderr"
    - "command_result.rc != 0"
  become: true
  become_method: sudo

# Se hace checkout a la rama 4.4
- name: Checkout de 4.4 kamailio version
  command: "{{ item }} chdir=/usr/src/kamailio/"
  with_items:
          - git checkout -b 4.4 origin/4.4
  register: command_result
  failed_when:
    - "'already exists' not in command_result.stderr"
    - "command_result.rc != 0"
  become: true
  become_method: sudo

# se hace el make prefix del kamailio.cfg (pasos de instalacion de kamailio desde ceros)
- name: Make Prefix kamailio.cfg
  shell: "make PREFIX={{ kamailio_location }} cfg chdir=/usr/src/kamailio"
  become: true
  become_method: sudo

# Se añaden los modulos que se quieren incluir por defecto en la instalacion
- name: Add the desired modules in modules.lst
  lineinfile:
          dest: /usr/src/kamailio/modules.lst
          regexp: '^include_modules='
          insertafter: '^include_modules= '
          line: 'include_modules= presence presence_xml app_python auth_ephemeral db_postgres ndb_redis presence tls uuid websocket'
  become: true
  become_method: sudo

# Se hace la copia del Makefile del modulo db_postgres, es necesario porque se customizó
- name: Copy of kamailio Makefile
  template: src=templates/Makefile dest=/usr/src/kamailio/modules/db_postgres/ owner=root group=root mode=755
  become: true
  become_method: sudo

# Se hace el make all y el make install
- name: Make of kamailio
  shell: "{{ item }} chdir=/usr/src/kamailio"
  with_items:
      - make all
      - make install
  become: true
  become_method: sudo
