---

# Hay tambien un template del archivo de configuracion de postgresql
# Deuda tecnica -- FIX ME--
# Hay que ver si se puede modificar el archivo despues de creado porque está dejando loguearse a postges sin necesidad de contraseña
- name: Modify of pg_hba.conf file (centos)
  template: src=roles/kamailio/templates/pg_hba.conf.j2 dest=/var/lib/pgsql/9.6/data/pg_hba.conf
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Copio archivo custom de configuracion de postgres, heredado de ICS
- name: Copy postgresql-fts.conf
  template: src=templates/postgresql-oml.conf dest=/var/lib/pgsql/9.6/data/
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Incluye postgres-oml en el .conf original
- name: Include postgresql-oml.conf in postgresql.conf
  lineinfile: >
    state=present
    dest=/var/lib/pgsql/9.6/data/postgresql.conf
    regexp="^include\s+'/var/lib/pgsql/9.6/data/postgresql-oml.conf'"
    insertafter=EOF
    line="include '/var/lib/pgsql/9.6/data/postgresql-oml.conf'"
  # TODO: reload (si cambio el archivo)
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Esto es para debian
- name: Modify of pg_hba.conf file (debian)
  template: src=roles/kamailio/templates/pg_hba.conf.j2 dest=/etc/postgresql/9.6/main/pg_hba.conf
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

# Restarteamos servicio
- name: Restart postgres service (centos)
  service: name=postgresql-9.6 state=restarted enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Restart postgres service (debian)
  service: name=postgresql state=restarted enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

# Se crea el usuario de postgres kamailio
- name: Create omnileads postgres user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name=omnileads password=omnileadsrw role_attr_flags=SUPERUSER

# Se crea el usuario de postgres kamailiorw
- name: Create omnileadsro postgres user
  postgresql_user: name=omnileadsro password=omnileadsro role_attr_flags=SUPERUSER
  become: yes
  become_method: sudo
  become_user: postgres
