# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---
- name: Instalacion de Omnileads con Asterisk en container
  hosts: omnileads
  vars:
          devops_tech: "{{ DEVOPS_TECH }}"
  pre_tasks:
      - name: Set the install prefix
        set_fact: install_prefix="~/opt/"
        tags: ['vagrant']

      - name: Create required directories for asterisk and kamailio config files
        file: "dest={{ item }} state=directory owner={{ usuario }} group={{ usuario }} mode=0755 recurse=yes"
        with_items:
          - /opt/omnileads/kamailio/etc/kamailio
          - /opt/omnileads/asterisk/etc/asterisk
          - /opt/omnileads/asterisk/var/lib/asterisk/agi-bin
        tags: ['vagrant']

  gather_facts: True

  roles:
          - {role: prerequisitos, tags: ['yum']}
          - {role: oml_server, tags: ['virtualenv']}
          - kamailio
          - {role: docker, tags: ['docker']}
          - {role: omniapp_second, tags: ['omniapp']}
          - deploy_supervision
