# Generated by Django 2.2.7 on 2020-02-14 15:45

import redis

from django.db import migrations
from django.conf import settings

from constance import config


def copiar_valores_constance(apps, schema_editor):
    """Realiza la copia de los valores de las variables en constance
    desde redis al nuevo backend en base de datos
    """
    redis_connection = redis.Redis(host=settings.REDIS_HOSTNAME, decode_responses=True)
    for redis_key in redis_connection.scan_iter():
        # eliminamos los caracteres de sufijos y prefijos de redis para obtener
        # el mero valor
        redis_value = redis_connection.get(redis_key)
        redis_key_str = redis_key.replace('constance:', '')
        redis_value_str = redis_value[1:-1].replace('\np1', '').replace('\'', '')
        config.__setattr__(redis_key_str, redis_value_str)


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0041_queue_musiconhold_playlist'),
    ]

    operations = [
        migrations.RunPython(copiar_valores_constance, reverse_code=migrations.RunPython.noop),
    ]
