# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:2.7.15

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - name: alejandrozf/docker-stuff:postgres-plpython-template1
    alias: plpython

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - /root/.cache/pip/

before_script:
  - mkdir -p ~/local/
  - cp oml_settings_local_pro.py ~/local/oml_settings_local.py
  - ln -s ~/local/oml_settings_local.py
  - mkdir -p /opt/omnileads/ominicontacto/
  - touch /opt/omnileads/ominicontacto/django.log
  - mkdir -p /opt/omnileads/static
  - mkdir -p /opt/omnileads/media_root
  # FIXME: what follows hack to simulate we have the 'sox' program, we should have the real program
  # as a docker image or installed by this script
  - touch sox
  - chmod +x sox
  - mv sox /usr/bin/
  - pip install -r requirements.txt

test:
  variables:
    POSTGRES_DB: kamailio
    POSTGRES_USER: kamailio
    POSTGRES_PASSWORD: kamailiorw
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - python manage.py test
