# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# El initdb de postgres toca ejecutarlo solo para centos
- name: Setup of postgresql
  command: "/usr/pgsql-9.6/bin/postgresql96-setup initdb"
  register: command_result
  failed_when:
    - "'is not empty' not in command_result.stdout"
    - "command_result.rc != 0"
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Con service starteas stopeas restarteas y habilitas servicios. Aca lo hacemos con postgres en centos
- name: Start and enable postgres service
  service: name=postgresql-9.6.service state=restarted enabled=yes
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

# En debian el servicio se llama diferente #quehijosdefrula
- name: Start and enable postgres service
  service: name=postgresql state=restarted enabled=yes
  become: yes
  become_method: sudo
  when: ansible_os_family == "Debian"

# Habilitamos y empezamos redis. Redis es necesario para rtpengine y para django-defender 
- name: Start and enable redis service
  service: name=redis state=restarted enabled=yes
  become: yes
  become_method: sudo
