---

#----------------------------------------------------------------------
# BD
#----------------------------------------------------------------------

- name: Initiate database
  sudo: yes
  command: >
    /sbin/service postgresql-{{pgsql_version}} initdb
    creates=/var/lib/pgsql/{{pgsql_version}}/data/postgresql.conf
  tags:
    - db
    - docker
    - docker-image

- name: Start PostgreSQL and enable at boot
  sudo: yes
  service: name=postgresql-{{pgsql_version}} enabled=yes state=started
  tags:
    - db
    - docker
    - docker-image

- name: Copy pg_hba.conf
  sudo: yes
  register: pg_hba_updated
  copy: src=pg_hba.conf dest=/var/lib/pgsql/{{pgsql_version}}/data/
  tags:
    - db
    - docker

- name: Copy postgresql-fts.conf
  sudo: yes
  template: src=etc/pgsql/postgresql-fts.conf dest=/var/lib/pgsql/{{pgsql_version}}/data/
  register: postgresql_fts_updated
  tags:
    - db
    - docker

- name: Include postgresql-fts.conf in postgresql.conf
  sudo: yes
  lineinfile: >
    state=present
    dest=/var/lib/pgsql/{{pgsql_version}}/data/postgresql.conf
    regexp="^include\s+'/var/lib/pgsql/{{pgsql_version}}/data/postgresql-fts.conf'"
    insertafter=EOF
    line="include '/var/lib/pgsql/{{pgsql_version}}/data/postgresql-fts.conf'"
  # TODO: reload (si cambio el archivo)
  tags:
    - db
    - docker

- name: Reload PostgreSql
  sudo: yes
  service: name=postgresql-{{pgsql_version}} state=reloaded
  when: pg_hba_updated.changed or postgresql_fts_updated.changed
  tags:
    - db
    - docker

- name: Create PostgreSql user
  postgresql_user: >
    name=ftsender
    password={{db_password}}
    role_attr_flags=CREATEDB,SUPERUSER
  sudo: yes
  sudo_user: postgres
  tags:
    - db
    - docker

- name: Create PostgreSql database
  postgresql_db: name=ftsender owner=ftsender
  sudo: yes
  sudo_user: postgres
  tags:
    - db
    - docker

- name: Check if plpython is installed
  shell: psql -c "select * from pg_language" ftsender | grep -q plpythonu
  sudo: yes
  sudo_user: postgres
  register: plpython_installed
  ignore_errors: True
  tags:
    - db
    - docker

- name: Install plpython if not installed
  command: createlang plpythonu ftsender
  sudo: yes
  sudo_user: postgres
  when: plpython_installed|failed
  tags:
    - db
    - docker

#----------------------------------------------------------------------
# Redis
#----------------------------------------------------------------------

- name: Start Redis and enable at boot
  sudo: yes
  service: name=redis enabled=yes state=started
  tags:
    - db
    - docker
    - docker-image
