---

- name: Create Gammu directory (to install Gammu)
  sudo: yes
  file: path=/opt/gammu state=directory owner=ftsender mode=0755
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Download Gammu sources
  sudo: yes
  sudo_user: ftsender
  get_url: >
    url={{ DOWNLOAD_GAMMU_URL }}
    dest=/opt/gammu/{{ DOWNLOAD_GAMMU_FILENAME }}
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Upload Gammu build script 
  when: gammu_installed|failed
  sudo: yes
  template: >
    src=bin/build_gammu.sh
    dest=/opt/gammu/
    owner=ftsender mode=0755
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Run Gammu build script 
  sudo: yes
  sudo_user: ftsender
  command: /opt/gammu/build_gammu.sh
  when: fts_distribution == "centos6" and gammu_installed|failed
  register: gammu_installed
  tags:
    - gammu
