---

- name: Create Gammu directory (to install Gammu)
  sudo: yes
  file: path=/opt/gammu state=directory owner=ftsender mode=0755
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Download Gammu sources
  sudo: yes
  sudo_user: ftsender
  get_url: >
    url={{ DOWNLOAD_GAMMU_URL }}
    dest=/opt/gammu/{{ DOWNLOAD_GAMMU_FILENAME }}
    sha256sum={{ DOWNLOAD_GAMMU_TARGZ_SHA256 }}
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Check if Gammu is installed 
  command: test -f /usr/local/bin/gammu
  register: gammu_installed
  ignore_errors: True
  when: fts_distribution == "centos6"
  tags:
    - gammu

- name: Upload Gammu build script 
  sudo: yes
  template: >
    src=bin/build_gammu.sh
    dest=/opt/gammu/
    owner=ftsender mode=0755
  when: fts_distribution == "centos6" and gammu_installed|failed
  tags:
    - gammu

- name: Upload Gammu test script 
  sudo: yes
  template: >
    src=bin/test_gammu.sh
    dest=/opt/gammu/
    owner=ftsender mode=0755
  when: fts_distribution == "centos6" and gammu_installed|failed
  tags:
    - gammu

- name: Upload Gammu install script 
  sudo: yes
  template: >
    src=bin/install_gammu.sh
    dest=/opt/gammu/
    owner=ftsender mode=0755
  when: fts_distribution == "centos6" and gammu_installed|failed
  tags:
    - gammu

- name: Run Gammu build script 
  sudo: yes
  sudo_user: ftsender
  command: /opt/gammu/build_gammu.sh
  when: fts_distribution == "centos6" and gammu_installed|failed 
  tags:
    - gammu

- name: Run Gammu test script 
  sudo: yes
  sudo_user: ftsender
  command: /opt/gammu/test_gammu.sh
  when: fts_distribution == "centos6" and gammu_installed|failed
  ignore_errors: True
  tags:
    - gammu

- name: Run Gammu install script 
  sudo: yes
  sudo_user: ftsender
  command: /opt/gammu/install_gammu.sh
  when: fts_distribution == "centos6" and gammu_installed|failed
  register: gammu_installed
  tags:
    - gammu


