---

- name: Check - RPM de EPEL 6 
  command: test -f /etc/yum.repos.d/epel.repo
  register: epel_installed
  ignore_errors: True

- name: Check - RPM de PostgreSql 9.3 
  command: test -f /etc/yum.repos.d/pgdg-93-centos.repo
  register: repo_pg_installed
  ignore_errors: True

- name: Instala RPM de EPEL 6
  when: epel_installed|failed
  sudo: yes
  yum: name=http://epel.mirror.mendoza-conicet.gob.ar/6/i386/epel-release-6-8.noarch.rpm state=present

- name: Instala RPM de PostgreSql 9.3
  when: repo_pg_installed|failed
  sudo: yes
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-6-i386/pgdg-centos93-9.3-1.noarch.rpm state=present

- name: Instala paquetes requeridos para FTSender
  sudo: yes
  yum: name={{item}} state=installed
  with_items:
    - postgresql93
    - postgresql93-contrib
    - postgresql93-server
    - python-devel
    - nginx
    - munin
    - redis
    - libselinux-python
    - python-psycopg2
    - python-virtualenv
    - rsync

- name: Initiate database
  sudo: yes
  command: service postgresql-9.3 initdb creates=/var/lib/pgsql/9.3/data/postgresql.conf

- name: Start PostgreSQL and enable at boot
  sudo: yes
  service: name=postgresql-9.3 enabled=yes state=started

- name: Start Nginx and enable at boot
  sudo: yes
  service: name=nginx enabled=yes state=started

- name: Copy pg_hba.conf
  sudo: yes
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/

- name: Create PostgreSql user
  postgresql_user: name=ftsender password={{db_password}}
  sudo: yes
  sudo_user: postgres

- name: Create PostgreSql database
  postgresql_db: name=ftsender owner=ftsender
  sudo: yes
  sudo_user: postgres

#- name: Remove temporary files from remote
#  file: path=/home/ftsender/build state=absent

- name: Create the required directories
  file: path={{item}} state=directory
  with_items:
    - /home/ftsender/deploy/app
    - /home/ftsender/deploy/local
    - /home/ftsender/deploy/media_root
    - /home/ftsender/deploy/static_root
    - /home/ftsender/deploy/log

- name: Upload built (rsync to /app)
  # Copies xxx/app to /home/ftsender/deploy/app (/app on dest is implicit)
  synchronize: src={{BUILD_DIR}} dest=/home/ftsender/deploy checksum=yes times=no

- name: Upload fts_web_settings_local.py
  template: src=fts_web_settings_local.py dest=/home/ftsender/deploy/local

# - name: Setup virtualenv
#   pip: requirements=XXXXXXXXX virtualenv=/my_app/venv virtualenv_site_packages=no
