---

#
# Deploy de la app
#
# Tags mas utiles:
#  - virtualenv: setup de virtualenv & requirements
#  - deploy: deploy de la APP (EXCEPTUANDO cambios en Nginx, virtualenv)
#
#

##
## Setup general, SO, packages, etc
##

- name: Check - RPM de EPEL 6 
  command: test -f /etc/yum.repos.d/epel.repo
  register: epel_installed
  ignore_errors: True
  tags:
    - yum

- name: Check - RPM de PostgreSql 9.3 
  command: test -f /etc/yum.repos.d/pgdg-93-centos.repo
  register: repo_pg_installed
  ignore_errors: True
  tags:
    - yum

- name: Instala RPM de EPEL 6
  when: epel_installed|failed
  sudo: yes
  yum: name=http://epel.mirror.mendoza-conicet.gob.ar/6/i386/epel-release-6-8.noarch.rpm state=present
  tags:
    - yum

- name: Instala RPM de PostgreSql 9.3
  when: repo_pg_installed|failed
  sudo: yes
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-6-i386/pgdg-centos93-9.3-1.noarch.rpm state=present
  tags:
    - yum

- name: Install Development tools
  sudo: yes
  yum: name="@Development tools" state=present
  tags:
    - yum

- name: Install basic packages
  sudo: yes
  yum: name={{item}} state=installed
  with_items:
    - libselinux-python
    - python-psycopg2
    - python-virtualenv
    - rsync
    - libxslt-devel
    - python-devel
    - ntp
    - ntpdate
  tags:
    - yum

- name: Install packages for required services
  sudo: yes
  yum: name={{item}} state=installed
  with_items:
    - postgresql93
    - postgresql93-contrib
    - postgresql93-server
    - postgresql93-devel
    - nginx
    - munin
    - redis
    - sox
  tags:
    - yum

- name: Check timezone
  command: diff -q /etc/localtime /usr/share/zoneinfo/America/Argentina/Cordoba
  register: clock_synchronized
  ignore_errors: True
  tags:
    - ntp

- name: Report timezone errors
  fail: msg="The server has an invalid TIMEZONE"
  when: clock_synchronized|failed
  tags:
    - ntp

- name: Start ntp and enable at boot
  sudo: yes
  service: name=ntpd enabled=yes state=started
  tags:
    - ntp

- name: Enable ntpdate
  sudo: yes
  service: name=ntpdate enabled=yes
  tags:
    - ntp

- name: Start Nginx and enable at boot
  sudo: yes
  service: name=nginx enabled=yes state=started
  tags:
    - nginx

- name: Configure Nginx
  sudo: yes
  template: src=etc/nginx/conf.d/ftsender.conf dest=/etc/nginx/conf.d/ftsender.conf owner=root group=root mode=0644
  tags:
    - nginx

- name: Setup pip
  ini_file: dest=/home/ftsender/.pip/pip.conf section=install option='download-cache' value='/home/ftsender/.pip/cache'
  tags:
    - virtualenv

##
## BD
##

- name: Initiate database
  sudo: yes
  command: service postgresql-9.3 initdb creates=/var/lib/pgsql/9.3/data/postgresql.conf
  tags:
    - db

- name: Start PostgreSQL and enable at boot
  sudo: yes
  service: name=postgresql-9.3 enabled=yes state=started
  tags:
    - db

- name: Copy pg_hba.conf
  sudo: yes
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/
  tags:
    - db

- name: Create PostgreSql user
  postgresql_user: name=ftsender password={{db_password}}
  sudo: yes
  sudo_user: postgres
  tags:
    - db

- name: Create PostgreSql database
  postgresql_db: name=ftsender owner=ftsender
  sudo: yes
  sudo_user: postgres
  tags:
    - db

##
## Deploy
##

- name: Create the required directories
  file: path={{item}} state=directory owner=ftsender mode=0755
  sudo: yes
  # /home/ftsender es incluido xq el permiso por default (0700) hace que
  # Nginx NO puda leer archivos estaticos y de media
  # TODO: la seguridad podria mejorarse moviendo statics y media a otro
  #   directorio fuera de /home
  with_items:
    - /etc/ftsender/asterisk
    - /home/ftsender
    - /home/ftsender/deploy
    - /home/ftsender/deploy/bin
    - /home/ftsender/deploy/app
    - /home/ftsender/deploy/local
    - /home/ftsender/deploy/media_root
    - /home/ftsender/deploy/static_root
    - /home/ftsender/deploy/log
    - /home/ftsender/deploy/run
  tags:
    - deploy

- name: Upload built (rsync to /app)
  # Copies xxx/app to /home/ftsender/deploy/app (/app on dest is implicit)
  synchronize: src={{BUILD_DIR}} dest=/home/ftsender/deploy delete=yes checksum=yes times=no
  tags:
    - deploy

- name: Setup virtualenv
  pip: requirements=/home/ftsender/deploy/app/requirements.txt virtualenv=/home/ftsender/deploy/virtualenv virtualenv_site_packages=no
  environment:
    PATH: /usr/pgsql-9.3/bin:{{ lookup('env', 'PATH') }}
  tags:
    - virtualenv

- name: Check - StarPy instalado 
  shell: find /home/ftsender/deploy/virtualenv -name starpy | grep -q starpy
  register: starpy_installed
  ignore_errors: True
  tags:
    - virtualenv

- name: Install starpy
  pip: name='git+git://github.com/asterisk/starpy.git@408f2636d8eb879c787073dccf147cc5fe734cba#egg=starpy' virtualenv=/home/ftsender/deploy/virtualenv
  when: starpy_installed|failed
  tags:
    - virtualenv

- name: Upload fts_web_settings_local.py
  template: src=fts_web_settings_local.py dest=/home/ftsender/deploy/local
  tags:
    - deploy

- name: Run Django syncdb
  django_manage: >
      command=syncdb
      app_path=/home/ftsender/deploy/app
      settings=fts_web.settings
      virtualenv=/home/ftsender/deploy/virtualenv
  environment:
    PYTHONPATH: '/home/ftsender/deploy/app:/home/ftsender/deploy/local'
  tags:
    - deploy

- name: Run Django migrations
  django_manage: >
      command=migrate
      app_path=/home/ftsender/deploy/app
      settings=fts_web.settings
      virtualenv=/home/ftsender/deploy/virtualenv
  environment:
    PYTHONPATH: '/home/ftsender/deploy/app:/home/ftsender/deploy/local'
  tags:
    - deploy

- name: Run Django collectstatic
  django_manage: >
      command=collectstatic
      app_path=/home/ftsender/deploy/app
      settings=fts_web.settings
      virtualenv=/home/ftsender/deploy/virtualenv
  environment:
    PYTHONPATH: '/home/ftsender/deploy/app:/home/ftsender/deploy/local'
  tags:
    - deploy

- name: Upload ftsender_uwsgi.ini
  template: src=ftsender_uwsgi.ini dest=/home/ftsender/deploy/local
  tags:
    - deploy

- name: Upload init script
  template: src=etc/init.d/ftsender-daemon dest=/etc/init.d/ftsender-daemon owner=root group=root mode=0755
  sudo: yes
  tags:
    - deploy

- name: Register FTSenser service
  service: name=ftsender-daemon enabled=yes
  sudo: yes
  tags:
    - deploy

- name: Upload scripts to deploy/bin
  template: src={{item}} dest=/home/ftsender/deploy/bin  mode=0755
  with_items:
    - run_uwsgi.sh
    - manage.sh
  tags:
    - deploy
