---

#----------------------------------------------------------------------
# Deploy de la app
#
# Tags mas utiles:
#  - virtualenv: setup de virtualenv & requirements
#  - deploy: deploy de la APP (EXCEPTUANDO cambios en otros
#       compoenentes, como Nginx)
#  - quick_deploy: deploy rapido de la APP (se saltea varios pasos)
#
# TODO:
#
# - ajustar configuracion de postgresql
# - hacer rsync a temporal, y hacer chequeos antes de copiar a productivo
# - al hacer copia, hacerla con comando remoto, para minimizar
#     probabilidades de inconsistencias si hay corte
# - crear ambiente de 'acceptance'
# - copiar BD e intentar migraciones en copia
# - reportar version instalada en remoto
#
# NO TIENE SOPORTE PARA:
#
# - resolver problemas con migraciones
# - actualizar requirements.txt (solo se instalaran los nuevos)
#
#----------------------------------------------------------------------

- name: Print fts_distribution
  # nos aseguramos q' "fts_distribution" haya sido definida.
  # si no fue definida, esta task generara un error
  debug: msg="fts_distribution es {{fts_distribution}}"

- name: Check fts_distribution
  fail: msg="fts_distribution con valor {{fts_distribution}} es invalida"
  when: (
    fts_distribution != "centos6" and
    fts_distribution != "elastix2" and
    fts_distribution != "elastix3"
    )

#----------------------------------------------------------------------
# Setup general, SO, packages, nginx, NTP, etc
#----------------------------------------------------------------------

# Elastix 2 facts:
#   (...)
#	"ansible_distribution": "CentOS",
#	"ansible_distribution_major_version": "5",
#	"ansible_distribution_release": "Final",
#	"ansible_distribution_version": "5.11",
#	"ansible_os_family": "RedHat",
#	"ansible_pkg_mgr": "yum",
#   (...)

# Elastix 3 facts:
#   (...)
#	"ansible_distribution": "Elastix",
#	"ansible_distribution_major_version": "3",
#	"ansible_distribution_release": "Final",
#	"ansible_distribution_version": "3.0",
#	"ansible_os_family": "Elastix",
#	"ansible_pkg_mgr": "yum",
#   (...)

- name: Check target server
  fail: msg="Target server isn't supported {{ansible_distribution}}"
  when: not (
    ansible_distribution == "CentOS" or
    ansible_distribution == "Elastix"
    )
  tags:
    - checks

- name: Setup sudoers.d/ftsender 
  template: >
    src=etc/sudoers.d/ftsender
    dest=/etc/sudoers.d/ftsender
    owner=root group=root mode=0440
  sudo: yes
  when: fts_distribution == "centos6"
  tags:
    - sudo

- include: packages.yml

- include: ntp.yml

- include: nginx.yml

- include: asterisk.yml

- include: bd.yml

- include: celery.yml

- include: deploy.yml
