---

#----------------------------------------------------------------------
# Deploy de la app
#
# Tags mas utiles:
#  - virtualenv: setup de virtualenv & requirements
#  - deploy: deploy de la APP (EXCEPTUANDO cambios en otros
#       compoenentes, como Nginx)
#  - quick_deploy: deploy rapido de la APP (se saltea varios pasos)
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Setup general, SO, packages, nginx, NTP, etc
#----------------------------------------------------------------------

- name: Check target server
  fail: msg="Target server isn't supported"
  when: >
    lookup("env","DO_CHECKS") != "no" and (
    ansible_distribution != "CentOS" or
    ansible_distribution_major_version|int != 6 )
  tags:
    - checks

- name: Setup sudoers.d/ftsender 
  template: >
    src=etc/sudoers.d/ftsender
    dest=/etc/sudoers.d/ftsender
    owner=root group=root mode=0440
  sudo: yes
  tags:
    - sudo

- include: packages.yml

- include: ntp.yml

- include: nginx.yml

- include: asterisk.yml

- include: bd.yml

- include: deploy.yml

