---

- name: Modify of pg_hba.conf file
  template: src=templates/pg_hba.conf.j2 dest=/var/lib/pgsql/9.6/data/pg_hba.conf
  become: true
  become_method: sudo

- name: Copy postgresql-fts.conf
  template: src=templates/postgresql-oml.conf dest=/var/lib/pgsql/{{ pgsql_version }}/data/
  become: true
  become_method: sudo

- name: Include postgresql-oml.conf in postgresql.conf
  lineinfile: >
    state=present
    dest=/var/lib/pgsql/{{ pgsql_version }}/data/postgresql.conf
    regexp="^include\s+'/var/lib/pgsql/{{ pgsql_version }}/data/postgresql-oml.conf'"
    insertafter=EOF
    line="include '/var/lib/pgsql/{{ pgsql_version }}/data/postgresql-oml.conf'"
  # TODO: reload (si cambio el archivo)
  become: true
  become_method: sudo

- name: Restart postgres service
  service: name=postgresql-9.6 state=restarted enabled=yes
  become: true
  become_method: sudo

- name: Create omnileads postgres user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name=omnileads password=omnileadsrw role_attr_flags=SUPERUSER

- name: Create omnileadsro postgres user
  postgresql_user: name=omnileadsro password=omnileadsro role_attr_flags=SUPERUSER
  become: yes
  become_method: sudo
  become_user: postgres

- name: Create kamailio database
  shell: createdb -O omnileads omnileads
  become: yes
  become_method: sudo
  become_user: postgres
  register: command_result
  failed_when:
    - "'already exists' not in command_result.stderr"
    - "'ya existe' not in command_result.stderr"
    - "command_result.rc != 0"

- name: Erase of default kamailio.cfg file
  shell: rm -rf {{ install_prefix }}kamailio/etc/kamailio/kamailio.cfg
  tags: postinstall

- name: Copy of oml-freepbx/kamailio-files to the desired destinations
  shell: "{{ item }} chdir={{ install_prefix }}ominicontacto/ominicontacto_voip"
  with_items:
      - cp kamailio-files/kamctlrc {{ install_prefix }}kamailio/etc/kamailio/

- name: Creation of kamailio file in /etc/default
  template: src=templates/kamailio.j2 dest=/etc/default/kamailio owner=root group=root mode=755

- name: Creation of kamailio.service file in systemd
  template: src=templates/kamailio.service.j2 dest=/etc/systemd/system/kamailio.service owner=root group=root mode=655