---
- hosts: ftsender
  gather_facts: '{{ lookup("env","DO_CHECKS") }}'
  roles:
    - ftsender_server
  remote_user: ftsender
  vars_files:
    - "roles/ftsender_server/defaults/vars-{{fts_distribution|default('centos6')}}.yml"
