---

# Lo mismo que se hizo con rtpengine y kamailio, se detecta si asterisk esta instalado o no para hacer o no la instalacion
- name: Check if Asterisk is installed
  shell: "test -f {{ install_prefix }}asterisk/sbin/asterisk || test -f /usr/sbin/asterisk"
  register: asterisk_installed
  ignore_errors: yes
  tags: asterisk
  become: true
  become_method: sudo

- debug: msg="Asterisk no está instalado, se procede a la instalación"
  when: asterisk_installed|failed
  tags: asterisk

- debug: msg="Asterisk ya se encuentra instalado se omite instalación"
  when: asterisk_installed|succeeded
  tags: asterisk

- include: install.yml
  when: asterisk_installed|failed
  tags: asterisk

- include: configuration.yml
  tags: asterisk

#- include: freepbx.yml
#  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
#  tags: freepbx
