---

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

#- name: Change key permission
#  file: path={{ install_prefix }}.ssh/ state=directory owner=omnileads group=omnileads mode=600 recurse=yes

- name: Create {{ usuario }} user and public key
  user: name={{ usuario }} generate_ssh_key=yes group={{ usuario }} ssh_key_bits=2048 state=present shell=/bin/bash
  become: true
  become_method: sudo

- name: Create the required directories
  file: "dest={{ item }} state=directory owner={{ usuario }} group={{ usuario }} mode=0755 recurse=yes"
  with_items:
          - "{{ install_prefix }}"
          - "{{ install_prefix }}.pip"
          - "{{ install_prefix }}ominicontacto"
          - "{{ install_prefix }}apidinstar"
          - "{{ install_prefix }}local"
          - "{{ install_prefix }}conf"
          - "{{ install_prefix }}wombat-json"
          - "{{ install_prefix }}bin"
          - "{{ install_prefix }}nginx_certs"
          - "{{ install_prefix }}media_root/reporte_campana"
          - "{{ install_prefix }}static"
          - "{{ install_prefix }}log"
          - /var/spool/dwgp/incoming/
          - /var/spool/dwgp/send/
          - /var/spool/dwgp/ussd_incoming/
          - /var/spool/dwgp/ussd_send
  when: desarrollo == 0

- name: Create directories for DB dumps
  file: "path={{item}} state=directory owner={{ usuario }} group=postgres mode=0770"
  with_items:
    - "{{ install_prefix }}dumps_bd_contacto"
  tags:
    - deploy
    - docker

#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

- name: Setup pip
  ini_file: >
    dest={{ install_prefix }}.pip/pip.conf
    section=install
    option='download-cache'
    value='{{ install_prefix }}.pip/cache'

- name: Upload built (rsync to /ominicontacto)
  # Copies xxx/app to {{ install_prefix }}ominicontacto (/ominicontacto on dest is implicit)
  synchronize: "src={{ build_dir }} dest={{ install_prefix }} delete=yes checksum=yes times=no"
  when: desarrollo == 0

- name: Clone of OML repository
  git: repo=git@bitbucket.org:omnileadsdesarrollo/ominicontacto.git dest={{ install_prefix }}ominicontacto/ accept_hostkey=yes
  when: desarrollo == 1
  ignore_errors: yes

- name: Checkout of desired branch
  git: repo=git@bitbucket.org:omnileadsdesarrollo/ominicontacto.git clone=no version={{ rama }} dest={{ install_prefix }}ominicontacto
  when: desarrollo == 1

- name: Change owner and group of ominicontacto
  file: "path={{ install_prefix }}ominicontacto owner={{ usuario }} group={{ usuario }} recurse=yes"

- name: Upgrade of python setuptools
  pip:
    name=setuptools
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv-2.7
    extra_args=--upgrade
  environment:
    PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin"
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"

- name: Setup virtualenv
  pip:
    requirements={{ install_prefix }}ominicontacto/requeriments.txt
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv-2.7
  environment:
      #PATH: /usr/pgsql-9.6/bin/:{{ lookup('env', 'PATH') }}:{{ install_prefix }}ominicontacto/virtualenv/bin
      PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin"
      PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"
- meta: clear_host_errors


- name: Upgrade of python setuptools
  pip:
    name=setuptools
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv
    extra_args=--upgrade
  environment:
    PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-9.6/bin"
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}/local'
  when: ansible_os_family == "Debian"

- name: Setup virtualenv
  pip: >
    requirements={{ install_prefix }}ominicontactorequeriments.txt
    virtualenv={{ install_prefix }}virtualenv
  when: ansible_os_family == "Debian"

#----------------------------------------------------------------------
# StarPy
#----------------------------------------------------------------------

- name: Check - StarPy instalado
  shell: find {{ install_prefix }}virtualenv -name starpy | grep -q starpy
  register: starpy_installed
  ignore_errors: True
  tags:
    - virtualenv
    - docker

- name: Install starpy
  pip: name={{ STARPY_PIP_URL }} virtualenv={{ install_prefix }}virtualenv
  when: starpy_installed|failed
  tags:
    - virtualenv
    - docker

#----------------------------------------------------------------------
# Upload of oml_settings_local.py
#----------------------------------------------------------------------

- name: Upload oml_settings_local.py
  template: "src=templates/oml_settings_local_debian.py dest={{ install_prefix }}local"
  when: ansible_os_family == "Debian"
- shell:  "mv oml_settings_local_debian.py oml_settings_local.py chdir={{ install_prefix }}local"
  when: ansible_os_family == "Debian"

- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local.py.j2 dest={{ install_prefix }}local/oml_settings_local.py
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"

- name: Creation of simbolic link of oml_settings_local.py
  file: state=link src={{ install_prefix }}local/oml_settings_local.py dest={{ install_prefix }}ominicontacto/oml_settings_local.py owner={{ usuario }} force=true
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"

#----------------------------------------------------------------------
# Upload of ics_settings_local.py
#----------------------------------------------------------------------

- name: Upload ics_settings_local.py
  template: src=ics_settings_local.py dest={{ install_prefix }}local
  tags:
    - deploy
    - quick_deploy
    - update_settings
    - docker

- name: Create ics_settings_local_customizations.py if doesnt exists
  file: >
    state=touch
    dest={{ install_prefix}}local/ics_settings_local_customizations.py
  tags:
    - deploy
    - quick_deploy
    - update_settings
    - docker

- name: Creation of simbolic link of ics_settings_local.py
  file: state=link src={{ install_prefix }}local/ics_settings_local.py dest={{ install_prefix }}ominicontacto/ics_settings_local.py owner={{ usuario }} force=true
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"