#! /bin/sh
#
# celery-worker-esperar-finaliza-campana
#
# chkconfig: - 90 10

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
USER=ftsender
GROUP=ftsender
CMD="/home/ftsender/deploy/virtualenv/bin/celery"

CONCURRENCY=4
WORKER_NAME="esperar-finaliza-campana"
QUEUE="esperar_y_finalizar_campana"

PIDFILE="/home/ftsender/deploy/run/celery-${WORKER_NAME}.pid"
LOGFILE="/home/ftsender/deploy/log/celery-${WORKER_NAME}.log"

export PYTHONPATH=/home/ftsender/deploy/app:/home/ftsender/deploy/local
export DJANGO_SETTINGS_MODULE=fts_web.settings

. /home/ftsender/deploy/virtualenv/bin/activate

# See how we were called.
case "$1" in
  start)
        echo -n "Starting Celery worker ${WORKER_NAME} ... "
        $CMD \
            -A fts_daemon.fts_celery_daemon.app \
            --no-color \
            --logfile=$LOGFILE \
            --loglevel=info \
            --queues=$QUEUE \
            --concurrency=$CONCURRENCY \
            --pidfile=$PIDFILE \
            --uid=$USER \
            --gid=$GROUP \
            --detach \
            worker

        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
  stop)
        echo -n "Stopping Celery worker ${WORKER_NAME} ... "
        pgrep -u ftsender -f -- --queues=$QUEUE > /dev/null || {
                echo "Celery worker ${WORKER_NAME} no esta corriendo..."
                echo_failure
                exit 1
        }

        su -l -s /bin/bash -c "kill $(cat $PIDFILE)" $USER
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
                echo_success
        else
                echo_failure
        fi
        echo
        ;;
   *)
        echo "Usage: $0 start|stop"
        exit 1
esac

exit $RETVAL
